### ISSUE TITLE
Overflow in Ni * Nj in coda-grib.c

### ISSUE THREAD

**Issue by schwehr** [stcorp/coda#47]
```
third_party/stcorp_coda/fuzz/coda_recognize_file_fuzzer crash-de1b3e5847b6bf90abb4b39bf5ce15b52c765ce6 

Running the target on file crash-de1b3e5847b6bf90abb4b39bf5ce15b52c765ce6 (91 bytes)
third_party/stcorp_coda/libcoda/coda-grib.c:1743:35: runtime error: signed integer overflow: 65500 * 56540 cannot be represented in type 'int'
    #0 0x5649e8feddf6 in read_grib1_message third_party/stcorp_coda/libcoda/coda-grib.c:1743:35
    #1 0x5649e8fdfc0d in coda_grib_reopen third_party/stcorp_coda/libcoda/coda-grib.c:3115:17
    #2 0x5649e9013ec6 in reopen_with_backend third_party/stcorp_coda/libcoda/coda-product.c:408:17
    #3 0x5649e9011a6d in open_file third_party/stcorp_coda/libcoda/coda-product.c:550:9
    #4 0x5649e90114ec in coda_recognize_file third_party/stcorp_coda/libcoda/coda-product.c:594:9
    #5 0x5649e8f6c22c in LLVMFuzzerTestOneInput third_party/stcorp_coda/fuzz/coda_recognize_file_fuzzer.cc:16:3
```

This is the trouble:

```c
            if (Ni != 65535 && Nj != 65535)
            {
                num_elements = Ni * Nj;
            }
```

Ni and Nj are both int values.

A possible fix:

```c
            if (Ni != 65535 && Nj != 65535)
            {
                num_elements = Ni * (long)Nj;
            }
```

**Comment by svniemeijer** [comment]
Fixed in 06fa8abaf974355dff9822817b19c80080eeca2d
