### ISSUE TITLE
coda_recognize_file_fuzzer: Crash in read_bytes

### ISSUE THREAD

**Issue by schwehr** [stcorp/coda#51]
```
#0 0x7fcee3833548 in __memmove_ssse3_back (/usr/grte/v4/lib64/libc.so.6+0xc2548)
--
  | #1 0x55fd54764b8c in read_bytes third_party/stcorp_coda/libcoda/coda-read-bytes.h:79:9
  | #2 0x55fd54767b46 in read_var_array third_party/stcorp_coda/libcoda/coda-netcdf.c:550:13
  | #3 0x55fd547645fd in coda_netcdf_reopen third_party/stcorp_coda/libcoda/coda-netcdf.c:901:9
  | #4 0x55fd5475b081 in reopen_with_backend third_party/stcorp_coda/libcoda/coda-product.c:402:17
  | #5 0x55fd547568db in open_file third_party/stcorp_coda/libcoda/coda-product.c:550:9
  | #6 0x55fd54756163 in coda_recognize_file third_party/stcorp_coda/libcoda/coda-product.c:594:9
  | #7 0x55fd54651fdf in LLVMFuzzerTestOneInput third_party/stcorp_coda/fuzz/coda_recognize_file_fuzzer.cc:19:3
```
and
```
0x60200000508f is located 1 bytes to the left of 1-byte region [0x602000005090,0x602000005091)
allocated by thread T0 here:
    #0 0x55859606213d in malloc third_party/llvm/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5585961742dc in read_var_array third_party/stcorp_coda/libcoda/coda-netcdf.c:542:16
    #2 0x558596170f08 in coda_netcdf_reopen third_party/stcorp_coda/libcoda/coda-netcdf.c:901:9
    #3 0x558596168403 in reopen_with_backend third_party/stcorp_coda/libcoda/coda-product.c:402:17
    #4 0x5585961650e8 in open_file third_party/stcorp_coda/libcoda/coda-product.c:550:9
    #5 0x558596164a2a in coda_recognize_file third_party/stcorp_coda/libcoda/coda-product.c:594:9
    #6 0x55859607b231 in LLVMFuzzerTestOneInput third_party/stcorp_coda/fuzz/coda_recognize_file_fuzzer.cc:19:3
```

Reproduces at https://github.com/stcorp/coda/commit/06fa8abaf974355dff9822817b19c80080eeca2d

**Comment by svniemeijer** [comment]
Do you have the testcase that triggered this?

**Comment by schwehr** [comment]
[testcase-5639383893409792.zip](https://github.com/stcorp/coda/files/4510443/testcase-5639383893409792.zip)

**Comment by svniemeijer** [comment]
Thanks. I found the issue. It seems we didn't account for negative sizes in the netcdf files. We will provide a fix soon.

**Comment by schwehr** [comment]
Thanks for the fix!  I verified locally that it does indeed fix the testcase crash.
