### ISSUE TITLE
harp_program_from_string_fuzzer: Direct-leak in harp_program_new

### ISSUE THREAD

**Issue by schwehr** [stcorp/coda#74]
```
==234513==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #1 0x55710a44067e in harp_program_new third_party/stcorp_harp/libharp/harp-program.c:47:31
    #2 0x55710a4265d2 in harp_operation_parser_parse libharp/harp-operation-parser.y:1682:17
    #3 0x55710a430235 in harp_program_from_string libharp/harp-operation-parser.y:1700:9
    #4 0x55710a229bcc in LLVMFuzzerTestOneInput third_party/stcorp_harp/fuzz/harp_program_from_string_fuzzer.cc:19:3
```

[testcase-4831660308955136.zip](https://github.com/stcorp/coda/files/4674435/testcase-4831660308955136.zip)

**Comment by schwehr** [comment]
whoops.  I will make an issue in harp
