### ISSUE TITLE
coda_recognize_file_fuzzer: Out-of-memory in coda_recognize_file_fuzzer

### ISSUE THREAD

**Issue by schwehr** [stcorp/coda#76]
```
   #8 0x56552655c278 in read_dim_array third_party/stcorp_coda/libcoda/coda-netcdf.c:131:19
    #9 0x56552655affb in coda_netcdf_reopen third_party/stcorp_coda/libcoda/coda-netcdf.c:898:9
    #10 0x565526551daf in reopen_with_backend third_party/stcorp_coda/libcoda/coda-product.c:404:17
    #11 0x56552654ea78 in open_file third_party/stcorp_coda/libcoda/coda-product.c:552:9
    #12 0x56552654e3ba in coda_recognize_file third_party/stcorp_coda/libcoda/coda-product.c:596:9
    #13 0x5655264610b1 in LLVMFuzzerTestOneInput third_party/stcorp_coda/fuzz/coda_recognize_file_fuzzer.cc:19:3
```

[testcase-5173175302488064.zip](https://github.com/stcorp/coda/files/4685667/testcase-5173175302488064.zip)

I have this fix locally that limits the number of dimensions, but maybe there is something else that can be done to catch non-sensical values.  At a minimum, there can't be more dimensions than the available remaining file size / minimum storage per dimension.  Can a negative number of dimensions ever be valid?  I'm guessing no.  Can things have zero dimensions in a netcdf file?

```c
    if (tag != 10)      /* NC_DIMENSION */
    {
        coda_set_error(CODA_ERROR_PRODUCT, "invalid netCDF file (invalid value for NC_DIMENSION tag)");
        return -1;
    }

    // BEGIN GOOGLE MODIFICATION
    // The testcase has 1920103026
    // fprintf(stderr, "num_dims %ld\n", *num_dims);
    if (*num_dims < 0 || 1000000)
    {
        coda_set_error(CODA_ERROR_PRODUCT, "Unreasonable num_dims (%ld) (%s:%d)",
                       *num_dims, __FILE__, __LINE__);
        return -1;
    }
    // END GOOGLE MODIFICATION

    *dim_length = malloc((*num_dims) * sizeof(int64_t));
    if (*dim_length == NULL)
    {
        coda_set_error(CODA_ERROR_OUT_OF_MEMORY, "out of memory (could not allocate %lu bytes) (%s:%u)",
                       (*num_dims) * sizeof(int64_t), __FILE__, __LINE__);
        return -1;
    }
```

**Comment by svniemeijer** [comment]
We already had a check for this in in read_length_value. It just wasn't applied to 32bit lengths yet. This is fixed in 9b442add1bfb18835392cd8bf708375fb5713132
